services:
  - type: web
    name: cafe-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
    buildCommand: flutter build web
    startCommand: flutter run -d web-server --web-port $PORT --web-hostname 0.0.0.0
